import os
import codecs

def fix_encoding(root_dir):
    # Common broken character mappings (UTF-8 read as ISO-8859-1 or Windows-1252/1254)
    # The actual string might be a mess. We will replace common wrong strings with correct ones.
    replacements = {
        'Ä±': 'ı',
        'ÄŸ': 'ğ',
        'Ã¼': 'ü',
        'ÅŸ': 'ş',
        'Ã¶': 'ö',
        'Ã§': 'ç',
        'Ä°': 'İ',
        'Äž': 'Ğ',
        'Ãœ': 'Ü',
        'Åž': 'Ş',
        'Ã–': 'Ö',
        'Ã‡': 'Ç',
        'Y': 'ş',
        '': 'ı',
        'erik': 'İçerik',
        'k': 'Çıkış',
        'Gvenlik': 'Güvenlik',
        'Editr': 'Editör',
        'Planlama': 'Planlama',
        'AkY': 'Akışı',
        '-ZEL': 'ÖZEL',
        'SON DAKKA': 'SON DAKİKA',
        'ATE?': 'ATEŞİ',
        'MA GoNo': 'MAÇ GÜNÜ',
        'canl': 'canlı',
        'krmz': 'kırmızı',
        'Blm': 'Bölüm',
        'Raporu': 'Raporu',
        'kaynaklarn': 'kaynaklarını',
        'ynetin': 'yönetin',
        'Bal': 'Bağlı',
        'Deil': 'Değil',
        'Sresi': 'Süresi',
        'Olutur': 'Oluştur',
        'Baarl': 'Başarılı',
        'Baarsz': 'Başarısız',
        'alYacak': 'çalışacak',
        'zellik': 'özellik',
        'Tm': 'Tüm',
        'Gster': 'Göster',
        'Gncellendi': 'Güncellendi',
        'Gncel': 'Güncel',
        'Grsel': 'Görsel',
        'Grnt': 'Görüntü',
        'D': 'Düşüş',
        'Art': 'Artış',
        'Gc': 'Gücü',
        'Dorulama': 'Doğrulama',
        'Balant': 'Bağlantı',
        'Says': 'Sayısı',
        'alYyor': 'Çalışıyor',
        'alYtr': 'Çalıştır',
        'sfrla': 'sıfırla',
        'A': 'Aç',
        'Ak': 'Açık',
        'Kapat': 'Kapat',
        'Kapal': 'Kapalı',
        'Dzenle': 'Düzenle',
        'Sil': 'Sil',
        'Bala': 'Başla',
        'Ykleniyor': 'Yükleniyor',
        'Kaydet': 'Kaydet',
        'Gnder': 'Gönder',
        'Gnderiliyor': 'Gönderiliyor',
        'Gnderildi': 'Gönderildi',
        'Hata': 'Hata',
        'Uyarı': 'Uyarı',
        'Baar': 'Başarı',
        'zet': 'Özet',
        'Aklama': 'Açıklama',
        'Balk': 'Başlık',
        'erik': 'İçerik',
        'Se': 'Seç',
        'Seenekler': 'Seçenekler',
        'Dier': 'Diğer',
        'Ekle': 'Ekle',
        'Yeni': 'Yeni',
        'Sonu': 'Sonuç',
        'Sonular': 'Sonuçlar',
        'Sayfa': 'Sayfa',
        'Geri': 'Geri',
        'leri': 'İleri',
        'ptal': 'İptal',
        'Tamam': 'Tamam',
        'Onayla': 'Onayla',
        'Reddet': 'Reddet',
        'Kabul Et': 'Kabul Et',
        'Vazge': 'Vazgeç',
        'Kapat': 'Kapat',
        'Ara': 'Ara',
        'Arama': 'Arama',
        'Filtrele': 'Filtrele',
        'Srala': 'Sırala',
        'Tarih': 'Tarih',
        'Zaman': 'Zaman',
        'Bugn': 'Bugün',
        'Dn': 'Dün',
        'Yarn': 'Yarın',
        'Bu Hafta': 'Bu Hafta',
        'Geen Hafta': 'Geçen Hafta',
        'Bu Ay': 'Bu Ay',
        'Geen Ay': 'Geçen Ay',
        'Bu Yl': 'Bu Yıl',
        'Geen Yl': 'Geçen Yıl',
        'Tm Zamanlar': 'Tüm Zamanlar',
        'Toplam': 'Toplam',
        'Ortalama': 'Ortalama',
        'En Yksek': 'En Yüksek',
        'En Dk': 'En Düşük',
        'Haberler': 'Haberler',
        'erikler': 'İçerikler',
        'Kullanc': 'Kullanıcı',
        'Kullanclar': 'Kullanıcılar',
        'Ynetici': 'Yönetici',
        'Yneticiler': 'Yöneticiler',
        'Misafir': 'Misafir',
        'Misafirler': 'Misafirler',
        'Sistem': 'Sistem',
        'Ayarlar': 'Ayarlar',
        'k': 'Çıkış',
        'Giri': 'Giriş',
        'Kayt': 'Kayıt',
        'Yenile': 'Yenile',
        'Yenileniyor': 'Yenileniyor',
        'Balan': 'Bağlan',
        'Balanyor': 'Bağlanıyor',
        'Baland': 'Bağlandı',
        'Balant Kesildi': 'Bağlantı Kesildi',
        'Balant Koptu': 'Bağlantı Koptu',
        'Balant Hatas': 'Bağlantı Hatası',
        'Bilinmeyen Hata': 'Bilinmeyen Hata',
        'Ltfen bekleyin': 'Lütfen bekleyin',
        'Ltfen tekrar deneyin': 'Lütfen tekrar deneyin',
        'rnek': 'Örnek',
        'rnein': 'Örneğin',
        'rnekler': 'Örnekler',
        'detaylar': 'detayları',
        'tm': 'tümü',
        'zellikler': 'özellikler',
        'deitir': 'değiştir',
        'gncelleyin': 'güncelleyin',
        'ayarlar': 'ayarları',
        'baaryla': 'başarıyla',
        'ilem': 'işlem',
        'retim': 'üretim',
        'alYmalar': 'Çalışmalar',
        'Gr': 'İçgörü',
        'grnyor': 'görünüyor',
        'olumlu': 'olumlu',
        'olumsuz': 'olumsuz',
        'etkileim': 'etkileşim',
        'payla': 'paylaş',
        'paylam': 'paylaşım',
        'Payla': 'Paylaş',
        'a': 'aç',
        'kapat': 'kapat',
        'ayarla': 'ayarla',
        'yaplandr': 'yapılandır',
        'kaynaklar': 'kaynakları',
        'says': 'sayısı',
        'bal': 'bağlı',
        'blm': 'bölüm',
        'deer': 'değer',
        'deerler': 'değerler',
        'sonu': 'sonuç',
        'sonular': 'sonuçlar',
        'zel': 'Özel',
        'zelletir': 'Özelleştir',
        'olmu': 'olmuş',
        'olmutur': 'olmuştur',
        'edilmi': 'edilmiş',
        'edilmitir': 'edilmiştir',
        'yaplm': 'yapılmış',
        'yaplmtr': 'yapılmıştır',
        'grlm': 'görülmüş',
        'grlmtr': 'görülmüştür',
        'alnm': 'alınmış',
        'alnmtr': 'alınmıştır',
        'verilmi': 'verilmiş',
        'verilmitir': 'verilmiştir',
        'salanm': 'sağlanmış',
        'salanmtr': 'sağlanmıştır',
        'bulunmu': 'bulunmuş',
        'bulunmutur': 'bulunmuştur',
        'gsterilmi': 'gösterilmiş',
        'gsterilmitir': 'gösterilmiştir',
        'belirtilmi': 'belirtilmiş',
        'belirtilmitir': 'belirtilmiştir',
        'kaydedilmi': 'kaydedilmiş',
        'kaydedilmitir': 'kaydedilmiştir',
        'gnderilmi': 'gönderilmiş',
        'gnderilmitir': 'gönderilmiştir',
        'alnyor': 'alınıyor',
        'veriliyor': 'veriliyor',
        'salanyor': 'sağlanıyor',
        'bulunuyor': 'bulunuyor',
        'gsteriliyor': 'gösteriliyor',
        'belirtiliyor': 'belirtiliyor',
        'kaydediliyor': 'kaydediliyor',
        'gnderiliyor': 'gönderiliyor',
        'yaplyor': 'yapılıyor',
        'ediliyor': 'ediliyor',
        'oluyor': 'oluyor',
        'olunuyor': 'olunuyor',
        'grlyor': 'görülüyor',
        'grnyor': 'görünüyor',
        'anlalyor': 'anlaşılıyor',
        'dnlyor': 'düşünülüyor',
        'bekleniyor': 'bekleniyor',
        'isteniyor': 'isteniyor',
        'gerekiyor': 'gerekiyor',
        'kalyor': 'kalıyor',
        'duruyor': 'duruyor',
        'geiyor': 'geçiyor',
        'geliyor': 'geliyor',
        'gidiyor': 'gidiyor',
        'olmutu': 'olmuştu',
        'edilmiti': 'edilmişti',
        'yaplmt': 'yapılmıştı',
        'grlmt': 'görülmüştü',
        'alnmt': 'alınmıştı',
        'verilmiti': 'verilmişti',
        'salanmt': 'sağlanmıştı',
        'bulunmutu': 'bulunmuştu',
        'gsterilmiti': 'gösterilmişti',
        'belirtilmiti': 'belirtilmişti',
        'kaydedilmiti': 'kaydedilmişti',
        'gnderilmiti': 'gönderilmişti',
        'Haber AkY': 'Haber Akışı',
        '-ZEL HABER': 'ÖZEL HABER',
        'MA GoNo': 'MAÇ GÜNÜ',
        'TRANSFER ATE?': 'TRANSFER ATEŞİ',
        'Gvenlik': 'Güvenlik',
        'grseli': 'görseli',
        'deerini': 'değerini',
        'kullanm': 'kullanım',
        'Alar': 'Açılar',
        'dzenle': 'düzenle',
        'olutur': 'oluştur',
        'kayna': 'kaynağı',
        'bal': 'bağlı',
        'ierik': 'içerik',
        'erik Merkezi': 'İçerik Merkezi',
        'k Yap': 'Çıkış Yap',
        'lm': 'Ölçüm',
        'ngr': 'Öngörü',
        'baar': 'başarı',
        'alYacak': 'çalışacak',
        'alYt': 'çalıştı',
        'dt': 'düştü',
        'dnYt': 'dönüştü',
        'Geliim': 'Gelişim',
        'strateji': 'strateji',
        'AI Strateji': 'AI Strateji',
        'Raporlar': 'Raporları',
        'sonular': 'sonuçları',
        'Analitik': 'Analitik',
        'Dashboard': 'Dashboard',
        '-': 'Öç',
        '-': 'Üş',
        'Y': 'ş',
        'z': 'öz',
        's': 'sı',
        't': 'tı',
        'd': 'dı',
        'n': 'nı',
        'l': 'lı',
        'r': 'rı',
        'y': 'yı',
        'm': 'mı',
        'c': 'cı',
        'k': 'kı',
        'p': 'pı',
        'v': 'vı',
        'b': 'bı',
        'z': 'zı',
        'o': 'ü',
        'O': 'Ü',
        '-': 'Ö',
        '?': 'Ş',
        'A': 'Ç',
        'I': 'İ',
        'G': 'Ğ',
        '?': 'Ş',
    }

    for dirpath, _, filenames in os.walk(root_dir):
        for filename in filenames:
            if filename.endswith(('.tsx', '.ts')):
                filepath = os.path.join(dirpath, filename)
                try:
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    original_content = content
                    for bad, good in replacements.items():
                        content = content.replace(bad, good)
                        
                    if content != original_content:
                        with open(filepath, 'w', encoding='utf-8') as f:
                            f.write(content)
                        print(f"Fixed encoding in: {filepath}")
                except Exception as e:
                    print(f"Failed {filepath}: {e}")

if __name__ == '__main__':
    fix_encoding('src/app')
    fix_encoding('src/components')
    fix_encoding('src/lib')